---@alias Inochi2D.InterpolateMode
---Round to nearest
---| "Nearest"
---Linear interpolation
---| "Linear"
---Round to nearest
---| "Stepped"
---Cubic interpolation
---| "Cubic"
---Interpolation using beziér splines
---| "Bezier"
